# =========================
# PROD PROFILE
# =========================

server.port=8080

# ===== Logging (prod: less verbose) =====
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN
logging.level.com.ssukssuk=INFO

# ===== JPA (prod: safer settings) =====
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===== Actuator security (prod) =====
management.endpoint.health.show-details=when-authorized
